//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS_DETALLE
    {
        public int FACD_ID { get; set; }
        public int FAC_ID { get; set; }
        public Nullable<int> REP_ID { get; set; }
        public Nullable<decimal> REP_VALOR { get; set; }
        public Nullable<int> SER_ID { get; set; }
        public Nullable<decimal> SER_VALOR { get; set; }
    
        public virtual FACTURAS FACTURAS { get; set; }
        public virtual REPUESTOS REPUESTOS { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
