//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURAS()
        {
            this.FACTURAS_DETALLE = new HashSet<FACTURAS_DETALLE>();
        }
    
        public int FAC_ID { get; set; }
        public int FAC_CLI_ID { get; set; }
        public int FAC_MEC_ID { get; set; }
        public decimal FAC_TOTAL_PARCIAL { get; set; }
        public decimal FAC_IVA { get; set; }
        public decimal FAC_DESCUENTO { get; set; }
        public decimal FAC_TOTAL { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS_DETALLE> FACTURAS_DETALLE { get; set; }
        public virtual MECANICOS MECANICOS { get; set; }
    }
}
