//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIOS()
        {
            this.FACTURAS_DETALLE = new HashSet<FACTURAS_DETALLE>();
        }
    
        public int SER_ID { get; set; }
        public string SER_DESCRIPCION { get; set; }
        public decimal SER_VALOR_MIN { get; set; }
        public Nullable<decimal> SER_VALOR_MAX { get; set; }
        public Nullable<System.DateTime> SER_ROW_CREATE { get; set; }
        public Nullable<System.DateTime> SER_ROW_MODIFY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS_DETALLE> FACTURAS_DETALLE { get; set; }
    }
}
