//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
        }
    
        public int CLI_ID { get; set; }
        public string CLI_PRIMER_NOMBRE { get; set; }
        public string CLI_SEGUNDO_NOMBRE { get; set; }
        public string CLI_PRIMER_APELLIDO { get; set; }
        public string CLI_SEGUNDO_APELLIDO { get; set; }
        public int CLI_TIPO_DOCUMENTO { get; set; }
        public int CLI_DOCUMENTO { get; set; }
        public string CLI_NUMERO_MOVIL { get; set; }
        public string CLI_DIRECCION { get; set; }
        public string CLI_EMAIL { get; set; }
        public decimal CLI_PRESUPUESTO { get; set; }
        public Nullable<System.DateTime> CLI_ROW_CREATE { get; set; }
        public Nullable<System.DateTime> CLI_ROW_MODIFY { get; set; }
    
        public virtual TIPODOCUMENTO TIPODOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
    }
}
