//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MECANICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MECANICOS()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
        }
    
        public int MEC_ID { get; set; }
        public string MEC_PRIMER_NOMBRE { get; set; }
        public string MEC_SEGUNDO_NOMBRE { get; set; }
        public string MEC_PRIMER_APELLIDO { get; set; }
        public string MEC_SEGUNDO_APELLIDO { get; set; }
        public Nullable<int> MEC_TIPO_DOCUMENTO { get; set; }
        public string MEC_DOCUMENTO { get; set; }
        public string MEC_NUMERO_MOVIL { get; set; }
        public string MEC_DIRECCION { get; set; }
        public string MEC_EMAIL { get; set; }
        public int MEC_ESTADO { get; set; }
        public Nullable<System.DateTime> MEC_ROW_CREATE { get; set; }
        public Nullable<System.DateTime> MEC_ROW_MODIFY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
        public virtual TIPODOCUMENTO TIPODOCUMENTO { get; set; }
    }
}
